name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: 
          pip install pyinstaller
          pip install openpyxl
          pip install numpy

      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: my-executable
          path: dist/app.exe
        


      - name: Build executable
        run: pyinstaller --onefile Main.py
